# Generated by Django 3.2 on 2025-03-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0005_residencia_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_vehiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], max_length=10)),
                ('cupos', models.IntegerField()),
            ],
        ),
    ]
