# Generated by Django 3.2 on 2025-03-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0009_auto_20250331_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='usuario',
        ),
    ]
