# Generated by Django 3.2 on 2025-03-31 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0011_auto_20250331_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('hora_ida', models.TimeField()),
                ('cupos_ida', models.IntegerField()),
                ('hora_vuelta', models.TimeField()),
                ('cupos_vuelta', models.IntegerField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos_dia', to='TransporteAPP.ruta')),
            ],
        ),
        migrations.DeleteModel(
            name='CupoPorDia',
        ),
    ]
