# Generated by Django 5.2 on 2025-04-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0015_alter_residencia_ubicacion_chat_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='timestamp',
            new_name='fecha_creacion',
        ),
    ]
