# Generated by Django 5.2 on 2025-04-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0016_rename_timestamp_mensaje_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='municipio',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
    ]
