# Generated by Django 5.2 on 2025-04-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0017_residencia_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='municipio_ruta',
            field=models.CharField(default='el rosal', max_length=100),
        ),
    ]
