# Generated by Django 3.2 on 2025-03-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0003_residencia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ResidenciaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='residencias/')),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='TransporteAPP.residencia')),
            ],
        ),
    ]
