# Generated by Django 3.2 on 2025-03-31 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0007_auto_20250329_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=20)),
                ('hora_ida', models.TimeField()),
                ('hora_vuelta', models.TimeField()),
                ('cupos_disponibles', models.IntegerField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos_dias', to='TransporteAPP.ruta')),
            ],
        ),
    ]
