# Generated by Django 3.2 on 2025-03-31 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TransporteAPP', '0010_remove_ruta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupopordia',
            name='cupos_disponibles',
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
