# Generated by Django 3.2 on 2025-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0014_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='municipio',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
