# Generated by Django 3.2 on 2025-04-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0015_ruta_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='municipio',
        ),
    ]
