# Generated by Django 3.2 on 2025-04-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransporteAPP', '0016_remove_ruta_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='ubicacion',
            field=models.URLField(max_length=500),
        ),
    ]
